version: '3.4'

services:
  app:
    container_name: nest_estate_backend
    restart: always
    build: .
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - '5000:5000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
         
  