name: Real estate application 
on: push
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_SENDER: ${{ secrets.SENDGRID_SENDER }}
          JWT_KEY: ${{ secrets.JWT_KEY}}
          CLOUD_NAME: ${{ secrets.CLOUD_NAME}}
          CLOUD_KEY: ${{ secrets.CLOUD_KEY }}
          CLOUD_KEY_SECRET: ${{ secrets.CLOUD_KEY_SECRET }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nest_estate_backend:latest .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nest_estate_backend:latest
     
      - name: Deploy to production
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          password: ${{ secrets.PRODUCTION_SERVER_PASSWORD }}
          port: 5000
          timeout: 2000s
          
          script: |
            docker stop nest_estate_backend || true
            docker rm nest_estate_backend || true
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/nest_estate_backend
            docker run -d --name nest_estate_backend -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/nest_estate_backend
         

      

